AdexWeb/Controllers/HyrjeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessLayer;
namespace AdexWeb.Controllers
{
    public class HyrjeController : Controller
    {
       [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(Users user)
        {
            UserBusiness bl = new UserBusiness();
         
           Users  perd = bl.Perdoruesit.Where(s => s.perdoruesi.Equals ( user.perdoruesi) && s.password.Equals ( user.password)).FirstOrDefault();
            //gjej username dhe password nga database
            if (perd != null)
            {
                Session["userID"] = perd.perdoruesi.ToString();

               return RedirectToAction("Index","Blank");
            }
            else

                return View();
        }
    }
}

AdexWeb/Views/Hyrje/Index.cshtml
@model BusinessLayer.Users

@{
    ViewBag.Title = "Index";
}



@using (Html.BeginForm("Index", "Hyrje", FormMethod.Post))
{
    <br />
    <fieldset>
        <br />
        <legend>Vendosni te dhenat e hyrjes</legend>

        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        @if (@ViewBag.Message != null)
        {
            <div style="border: 1px solid red">
                @ViewBag.Message
            </div>
        }
        <table>
            <tr>
                <td>@Html.LabelFor(Model => Model.perdoruesi)    </td>
                <td>@Html.TextBoxFor(Model => Model.perdoruesi)</td>
                <td>@Html.ValidationMessageFor(Model => Model.perdoruesi)</td>
            </tr>
            <tr><td></td></tr>
            <tr>
                <td>
                    @Html.LabelFor(Model => Model.password)
                </td>
                <td>
                    @Html.PasswordFor(Model => Model.password)
                </td>
                <td>
                    @Html.ValidationMessageFor(Model => Model.password)
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <input type="submit" value="Login" />
                </td>
                <td></td>
            </tr>
        </table>
    </fieldset> 
}