AdexWeb/Controllers/BlankController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AdexWeb.Controllers
{
    public class BlankController : Controller
    {
        // GET: Blank
        public ActionResult Index()
        {


            return View();
        }
    }
}

AdexWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("ADEX Online", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        
            <div class="navbar-collapse collapse">
           
                
                @*<ul class="nav navbar-nav navbar-right">*@
                    @*<li>@Html.ActionLink("Perdoruesit", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>*@
                    @if (Session["userID"] == null)
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li>@Html.ActionLink("Hyrje", "Index", "Hyrje")</li>
                        </ul>
                    }
                    else
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li>@Html.ActionLink("Perdoruesit", "Index", "Perdoruesi", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                            <li>@Html.ActionLink(Session["userID"].ToString(), "Index", "Blank")</li>
                            <li>@Html.ActionLink("Largohu", "Index", "Home")</li>

                        </ul>   
                         <ul class="nav navbar-nav">
                             <li class="dropdown">
                                 <a class="dropdown-toggle" data-toggle="dropdown" href="#">Klienti <span class="caret"></span></a>
                                 <ul class="dropdown-menu">
                                     <li>@Html.ActionLink("Agjensite", "Index", "Agjensi")</li>
                                     <li>@Html.ActionLink("Klientet", "Index", "Klienti")</li>
                                    
                                 </ul>
                             </li>

                             <li class="dropdown">
                                 <a class="dropdown-toggle" data-toggle="dropdown" href="#">Shperndarja <span class="caret"></span></a>
                                 <ul class="dropdown-menu">
                                     <li>@Html.ActionLink("Shoferet", "Index", "Shoferi")</li>
                                     <li>@Html.ActionLink("Dispecherat", "Index", "Dispecher")</li>
                                     <li>@Html.ActionLink("Magazinat", "Index", "Magazina")</li>  
                                 </ul>
                             </li>

                             <li class="dropdown">
                                 <a class="dropdown-toggle" data-toggle="dropdown" href="#">Konfigurime <span class="caret"></span></a>
                                 <ul class="dropdown-menu">
                                     <li>@Html.ActionLink("Zonat", "Index", "Zona")</li>
                                     <li>@Html.ActionLink("Sherbimet", "Index", "Lloji")</li>
                                     <li>@Html.ActionLink("Cmimet", "Index", "Cmimet")</li>
                                     <li>@Html.ActionLink("Skontot", "Index", "Skonto")</li>      
                                 </ul>
                             </li>
                        </ul>
                      
                    }
                @*</ul>*@
                @*@Html.Partial("_LoginPartial")*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - ADEX Online</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>